### PR TITLE
Clustering dashboard

### PR DESCRIPTION
**Pull request by ang2887**
I added unsupervised_dashboard.py as script this time)

### CODE REVIEW

**Comment by ang2887** [comment]
I would be happy to receive your feedback on how to improve it. Thank you!

**Comment by a-arad** [comment]
looks good at a glance :) 
will now take a closer look

**Comment by ang2887** [comment]
Thanks)

**Comment by a-arad** [comment]
it works!

nice job.

there are merge conflicts since i reorganized the project structure so I will cherrypick only the python script that generates the dashboard.

**Comment by ang2887** [comment]
Thanks!   
  
  
  
  
  
  
  

  
  
>

**Pull request closed without merging**
